# Generated by Django 4.2.1 on 2023-06-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='realname',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
