# Generated by Django 4.2.1 on 2023-06-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_account_realname_alter_account_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='sex',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
