# Generated by Django 4.2.1 on 2023-06-23 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_account_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='auth_key',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
